package com.med.ods.entity;
// Generated Dec 19, 2016 4:16:39 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Constants generated by hbm2java
 */
@Entity
@Table(name = "CONSTANTS")
public class Constants implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9033601160592950604L;
	private Integer id;
	private String srcParam;
	private String dstParam;
	private String value;

	public Constants() {
	}

	public Constants(String srcParam, String dstParam, String value) {
		this.srcParam = srcParam;
		this.dstParam = dstParam;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SRC_PARAM", length = 20)
	public String getSrcParam() {
		return this.srcParam;
	}

	public void setSrcParam(String srcParam) {
		this.srcParam = srcParam;
	}

	@Column(name = "DST_PARAM", length = 100)
	public String getDstParam() {
		return this.dstParam;
	}

	public void setDstParam(String dstParam) {
		this.dstParam = dstParam;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
