package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NotiUnsubscrTemp generated by hbm2java
 */
@Entity
@Table(name = "NOTI_UNSUBSCR_TEMP")
public class NotiUnsubscrTemp implements java.io.Serializable {

	private NotiUnsubscrTempId id;
	private NotiSubscrTbl notiSubscrTbl;
	private Person person;
	private Boolean status;

	public NotiUnsubscrTemp() {
	}

	public NotiUnsubscrTemp(NotiUnsubscrTempId id, NotiSubscrTbl notiSubscrTbl, Person person) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.person = person;
	}

	public NotiUnsubscrTemp(NotiUnsubscrTempId id, NotiSubscrTbl notiSubscrTbl, Person person, Boolean status) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.person = person;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "subscrId", column = @Column(name = "SUBSCR_ID", nullable = false)),
			@AttributeOverride(name = "persId", column = @Column(name = "PERS_ID", nullable = false)) })
	public NotiUnsubscrTempId getId() {
		return this.id;
	}

	public void setId(NotiUnsubscrTempId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCR_ID", nullable = false, insertable = false, updatable = false)
	public NotiSubscrTbl getNotiSubscrTbl() {
		return this.notiSubscrTbl;
	}

	public void setNotiSubscrTbl(NotiSubscrTbl notiSubscrTbl) {
		this.notiSubscrTbl = notiSubscrTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERS_ID", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
