package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NotiAttribute generated by hbm2java
 */
@Entity
@Table(name = "NOTI_ATTRIBUTE")
public class NotiAttribute implements java.io.Serializable {

	private NotiAttributeId id;
	private NotiPool notiPool;
	private String value;

	public NotiAttribute() {
	}

	public NotiAttribute(NotiAttributeId id, NotiPool notiPool) {
		this.id = id;
		this.notiPool = notiPool;
	}

	public NotiAttribute(NotiAttributeId id, NotiPool notiPool, String value) {
		this.id = id;
		this.notiPool = notiPool;
		this.value = value;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "notiId", column = @Column(name = "NOTI_ID", nullable = false)),
			@AttributeOverride(name = "keys", column = @Column(name = "KEYS", nullable = false)) })
	public NotiAttributeId getId() {
		return this.id;
	}

	public void setId(NotiAttributeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NOTI_ID", nullable = false, insertable = false, updatable = false)
	public NotiPool getNotiPool() {
		return this.notiPool;
	}

	public void setNotiPool(NotiPool notiPool) {
		this.notiPool = notiPool;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
