package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotiPool generated by hbm2java
 */
@Entity
@Table(name = "NOTI_POOL")
public class NotiPool implements java.io.Serializable {

	private Integer notiId;
	private Boolean sent;
	private String title;
	private String body;
	private Integer personOwner;
	private String target;
	private String type;
	private Date lastUpdDttm;
	private Date createdAt;
	private Set<NotiAttribute> notiAttributes = new HashSet<NotiAttribute>(0);

	public NotiPool() {
	}

	public NotiPool(Boolean sent, String title, String body, Integer personOwner, String target, String type, Date createdAt,
			Date lastUpdDttm, Set<NotiAttribute> notiAttributes) {
		this.sent = sent;
		this.title = title;
		this.body = body;
		this.personOwner = personOwner;
		this.target = target;
		this.type = type;
		this.lastUpdDttm = lastUpdDttm;
		this.notiAttributes = notiAttributes;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NOTI_ID", unique = true, nullable = false)
	public Integer getNotiId() {
		return this.notiId;
	}

	public void setNotiId(Integer notiId) {
		this.notiId = notiId;
	}

	@Column(name = "SENT")
	public Boolean getSent() {
		return this.sent;
	}

	public void setSent(Boolean sent) {
		this.sent = sent;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "BODY")
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "PERSON_OWNER")
	public Integer getPersonOwner() {
		return this.personOwner;
	}

	public void setPersonOwner(Integer personOwner) {
		this.personOwner = personOwner;
	}

	@Column(name = "TARGET")
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_AT", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notiPool")
	public Set<NotiAttribute> getNotiAttributes() {
		return this.notiAttributes;
	}

	public void setNotiAttributes(Set<NotiAttribute> notiAttributes) {
		this.notiAttributes = notiAttributes;
	}

}
