package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotiLogId generated by hbm2java
 */
@Embeddable
public class NotiLogId implements java.io.Serializable {

	private int persId;
	private int notiId;

	public NotiLogId() {
	}

	public NotiLogId(int persId, int notiId) {
		this.persId = persId;
		this.notiId = notiId;
	}

	@Column(name = "PERS_ID", nullable = false)
	public int getPersId() {
		return this.persId;
	}

	public void setPersId(int persId) {
		this.persId = persId;
	}

	@Column(name = "NOTI_ID", nullable = false)
	public int getNotiId() {
		return this.notiId;
	}

	public void setNotiId(int notiId) {
		this.notiId = notiId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotiLogId))
			return false;
		NotiLogId castOther = (NotiLogId) other;

		return (this.getPersId() == castOther.getPersId()) && (this.getNotiId() == castOther.getNotiId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersId();
		result = 37 * result + this.getNotiId();
		return result;
	}

}
