package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotiAttributeId generated by hbm2java
 */
@Embeddable
public class NotiAttributeId implements java.io.Serializable {

	private int notiId;
	private String keys;

	public NotiAttributeId() {
	}

	public NotiAttributeId(int notiId, String keys) {
		this.notiId = notiId;
		this.keys = keys;
	}

	@Column(name = "NOTI_ID", nullable = false)
	public int getNotiId() {
		return this.notiId;
	}

	public void setNotiId(int notiId) {
		this.notiId = notiId;
	}

	@Column(name = "KEYS", nullable = false)
	public String getKey() {
		return this.keys;
	}

	public void setKey(String keys) {
		this.keys = keys;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotiAttributeId))
			return false;
		NotiAttributeId castOther = (NotiAttributeId) other;

		return (this.getNotiId() == castOther.getNotiId()) && ((this.getKey() == castOther.getKey())
				|| (this.getKey() != null && castOther.getKey() != null && this.getKey().equals(castOther.getKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNotiId();
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		return result;
	}

}
