package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotiUnsubscrTempId generated by hbm2java
 */
@Embeddable
public class NotiUnsubscrTempId implements java.io.Serializable {

	private String subscrId;
	private int persId;

	public NotiUnsubscrTempId() {
	}

	public NotiUnsubscrTempId(String subscrId, int persId) {
		this.subscrId = subscrId;
		this.persId = persId;
	}

	@Column(name = "SUBSCR_ID", nullable = false)
	public String getSubscrId() {
		return this.subscrId;
	}

	public void setSubscrId(String subscrId) {
		this.subscrId = subscrId;
	}

	@Column(name = "PERS_ID", nullable = false)
	public int getPersId() {
		return this.persId;
	}

	public void setPersId(int persId) {
		this.persId = persId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotiUnsubscrTempId))
			return false;
		NotiUnsubscrTempId castOther = (NotiUnsubscrTempId) other;

		return ((this.getSubscrId() == castOther.getSubscrId()) || (this.getSubscrId() != null
				&& castOther.getSubscrId() != null && this.getSubscrId().equals(castOther.getSubscrId())))
				&& (this.getPersId() == castOther.getPersId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSubscrId() == null ? 0 : this.getSubscrId().hashCode());
		result = 37 * result + this.getPersId();
		return result;
	}

}
