package com.med.ods.entity;
// Generated Aug 31, 2017 2:07:20 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotiSubscrPerson generated by hbm2java
 */
@Entity
@Table(name = "NOTI_SUBSCR_PERSON")
public class NotiSubscrPerson implements java.io.Serializable {

	private NotiSubscrPersonId id;
	private NotiSubscrTbl notiSubscrTbl;
	private PersLoginDevice persLoginDevice;
	private String status;
	private Date lastUpdDttm;

	public NotiSubscrPerson() {
	}

	public NotiSubscrPerson(NotiSubscrPersonId id, NotiSubscrTbl notiSubscrTbl, PersLoginDevice persLoginDevice) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.persLoginDevice = persLoginDevice;
	}

	public NotiSubscrPerson(NotiSubscrPersonId id, NotiSubscrTbl notiSubscrTbl, PersLoginDevice persLoginDevice,
			String status, Date lastUpdDttm) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.persLoginDevice = persLoginDevice;
		this.status = status;
		this.lastUpdDttm = lastUpdDttm;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "subscrId", column = @Column(name = "SUBSCR_ID", nullable = false)),
			@AttributeOverride(name = "persLoginDevice", column = @Column(name = "PERS_LOGIN_DEVICE", nullable = false)) })
	public NotiSubscrPersonId getId() {
		return this.id;
	}

	public void setId(NotiSubscrPersonId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCR_ID", nullable = false, insertable = false, updatable = false)
	public NotiSubscrTbl getNotiSubscrTbl() {
		return this.notiSubscrTbl;
	}

	public void setNotiSubscrTbl(NotiSubscrTbl notiSubscrTbl) {
		this.notiSubscrTbl = notiSubscrTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERS_LOGIN_DEVICE", nullable = false, insertable = false, updatable = false)
	public PersLoginDevice getPersLoginDevice() {
		return this.persLoginDevice;
	}

	public void setPersLoginDevice(PersLoginDevice persLoginDevice) {
		this.persLoginDevice = persLoginDevice;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

}
