package com.med.ods.entity;
// Generated Aug 24, 2017 6:22:56 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotiSubscrTbl generated by hbm2java
 */
@Entity
@Table(name = "NOTI_SUBSCR_TBL")
public class NotiSubscrTbl implements java.io.Serializable {

	private Integer subscrId;
	private Integer isActive;
	private String type;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private String subscrName;
	private Integer allUserFlag;
	private String subscrDescr;
	private Set<NotiUnsubscrTemp> notiUnsubscrTemps = new HashSet<NotiUnsubscrTemp>(0);
	private Set<NotiSubscrPerson> notiSubscrPersons = new HashSet<NotiSubscrPerson>(0);
	private Set<NotiPersonSubscr> notiPersonSubscrs = new HashSet<NotiPersonSubscr>(0);

	public NotiSubscrTbl() {
	}

	public NotiSubscrTbl(Integer subscrId) {
		this.subscrId = subscrId;
	}

	public NotiSubscrTbl(Integer subscrId, Integer isActive, String type, Date lastUpdDttm,
			String subscrName,Integer allUserFlag,Integer lastUpdOprid,String subscrDescr,
			Set<NotiUnsubscrTemp> notiUnsubscrTemps, Set<NotiSubscrPerson> notiSubscrPersons) {
		this.subscrId = subscrId;
		this.isActive = isActive;
		this.type = type;
		this.lastUpdDttm = lastUpdDttm;
		this.notiUnsubscrTemps = notiUnsubscrTemps;
		this.notiSubscrPersons = notiSubscrPersons;
		this.subscrName = subscrName;
		this.allUserFlag = allUserFlag;
		this.lastUpdOprid = lastUpdOprid;
		this.subscrDescr = subscrDescr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "SUBSCR_ID", unique = true, nullable = false)
	public Integer getSubscrId() {
		return this.subscrId;
	}

	public void setSubscrId(Integer subscrId) {
		this.subscrId = subscrId;
	}

	@Column(name = "IS_ACTIVE")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	
	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@Column(name = "SUBSCR_NAME",length = 255)
	public String getSubscrName() {
		return subscrName;
	}

	public void setSubscrName(String subscrName) {
		this.subscrName = subscrName;
	}
	@Column(name = "SUBSCR_DESCR",length = 255)
	public String getSubscrDescr() {
		return subscrDescr;
	}

	public void setSubscrDescr(String subscrDescr) {
		this.subscrDescr = subscrDescr;
	}

	@Column(name = "ALL_USER_FLAG")
	public Integer getAllUserFlag() {
		return allUserFlag;
	}

	public void setAllUserFlag(Integer allUserFlag) {
		this.allUserFlag = allUserFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notiSubscrTbl")
	public Set<NotiUnsubscrTemp> getNotiUnsubscrTemps() {
		return this.notiUnsubscrTemps;
	}

	public void setNotiUnsubscrTemps(Set<NotiUnsubscrTemp> notiUnsubscrTemps) {
		this.notiUnsubscrTemps = notiUnsubscrTemps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notiSubscrTbl")
	public Set<NotiSubscrPerson> getNotiSubscrPersons() {
		return this.notiSubscrPersons;
	}

	public void setNotiSubscrPersons(Set<NotiSubscrPerson> notiSubscrPersons) {
		this.notiSubscrPersons = notiSubscrPersons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notiSubscrTbl")
	public Set<NotiPersonSubscr> getNotiPersonSubscrs() {
		return notiPersonSubscrs;
	}

	public void setNotiPersonSubscrs(Set<NotiPersonSubscr> notiPersonSubscrs) {
		this.notiPersonSubscrs = notiPersonSubscrs;
	}
	
	
}
