package com.med.ods.entity;
// Generated Oct 23, 2017 6:41:17 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotiPersonSubscr generated by hbm2java
 */
@Entity
@Table(name = "NOTI_PERSON_SUBSCR")
public class NotiPersonSubscr implements java.io.Serializable {

	private NotiPersonSubscrId id;
	private NotiSubscrTbl notiSubscrTbl;
	private Person person;
	private Date lastUpdDttm;
	private String status;

	public NotiPersonSubscr() {
	}

	public NotiPersonSubscr(NotiPersonSubscrId id, NotiSubscrTbl notiSubscrTbl, Person person) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.person = person;
	}

	public NotiPersonSubscr(NotiPersonSubscrId id, NotiSubscrTbl notiSubscrTbl, Person person, Date lastUpdDttm,
			String status) {
		this.id = id;
		this.notiSubscrTbl = notiSubscrTbl;
		this.person = person;
		this.lastUpdDttm = lastUpdDttm;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "subscrId", column = @Column(name = "SUBSCR_ID", nullable = false)),
			@AttributeOverride(name = "persId", column = @Column(name = "PERS_ID", nullable = false)) })
	public NotiPersonSubscrId getId() {
		return this.id;
	}

	public void setId(NotiPersonSubscrId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCR_ID", nullable = false, insertable = false, updatable = false)
	public NotiSubscrTbl getNotiSubscrTbl() {
		return this.notiSubscrTbl;
	}

	public void setNotiSubscrTbl(NotiSubscrTbl notiSubscrTbl) {
		this.notiSubscrTbl = notiSubscrTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERS_ID", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 23)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
