package com.med.ods.entity;
// Generated Dec 19, 2016 4:16:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsListTbl generated by hbm2java
 */
@Entity
@Table(name = "PERMS_LIST_TBL")
public class PermsListTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7794634551369168337L;
	private String permsListId;
	private String listName;
	private String descr;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private Set<PermsList> permsLists = new HashSet<PermsList>(0);
	private Set<PermsPersGroupTbl> permsPersGroupTbls = new HashSet<PermsPersGroupTbl>(0);

	public PermsListTbl() {
	}

	public PermsListTbl(String permsListId) {
		this.permsListId = permsListId;
	}

	public PermsListTbl(String permsListId, String listName, String descr, Date lastUpdDttm, Integer lastUpdOprid,
			Set<PermsList> permsLists, Set<PermsPersGroupTbl> permsPersGroupTbls) {
		this.permsListId = permsListId;
		this.listName = listName;
		this.descr = descr;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
		this.permsLists = permsLists;
		this.permsPersGroupTbls = permsPersGroupTbls;
	}

	@Id

	@Column(name = "PERMS_LIST_ID", unique = true, nullable = false, length = 10)
	public String getPermsListId() {
		return this.permsListId;
	}

	public void setPermsListId(String permsListId) {
		this.permsListId = permsListId;
	}

	@Column(name = "LIST_NAME", length = 45)
	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	@Column(name = "DESCR")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsListTbl", cascade = CascadeType.ALL)
	public Set<PermsList> getPermsLists() {
		return this.permsLists;
	}

	public void setPermsLists(Set<PermsList> permsLists) {
		this.permsLists = permsLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsListTbl")
	public Set<PermsPersGroupTbl> getPermsPersGroupTbls() {
		return this.permsPersGroupTbls;
	}

	public void setPermsPersGroupTbls(Set<PermsPersGroupTbl> permsPersGroupTbls) {
		this.permsPersGroupTbls = permsPersGroupTbls;
	}

}
