package com.med.ods.entity;
// Generated Dec 19, 2016 4:16:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsPersGroup generated by hbm2java
 */
@Entity
@Table(name = "PERMS_PERS_GROUP")
public class PermsPersGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3947323127682231050L;
	private PermsPersGroupId id;
	private PermsPersGroupTbl permsPersGroupTbl;
	private PersAccount persAccount;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;

	public PermsPersGroup() {
	}

	public PermsPersGroup(PermsPersGroupId id, PermsPersGroupTbl permsPersGroupTbl, PersAccount persAccount) {
		this.id = id;
		this.permsPersGroupTbl = permsPersGroupTbl;
		this.persAccount = persAccount;
	}

	public PermsPersGroup(PermsPersGroupId id, PermsPersGroupTbl permsPersGroupTbl, PersAccount persAccount,
			Date lastUpdDttm, Integer lastUpdOprid) {
		this.id = id;
		this.permsPersGroupTbl = permsPersGroupTbl;
		this.persAccount = persAccount;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "persId", column = @Column(name = "PERS_ID", nullable = false)),
			@AttributeOverride(name = "permsPersGroupId", column = @Column(name = "PERMS_PERS_GROUP_ID", nullable = false, length = 10)) })
	public PermsPersGroupId getId() {
		return this.id;
	}

	public void setId(PermsPersGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMS_PERS_GROUP_ID", nullable = false, insertable = false, updatable = false)
	public PermsPersGroupTbl getPermsPersGroupTbl() {
		return this.permsPersGroupTbl;
	}

	public void setPermsPersGroupTbl(PermsPersGroupTbl permsPersGroupTbl) {
		this.permsPersGroupTbl = permsPersGroupTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERS_ID", nullable = false, insertable = false, updatable = false)
	public PersAccount getPersAccount() {
		return this.persAccount;
	}

	public void setPersAccount(PersAccount persAccount) {
		this.persAccount = persAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

}
