package com.med.ods.entity;
// Generated Mar 23, 2017 4:05:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsModuleTbl generated by hbm2java
 */
@Entity
@Table(name = "PERMS_MODULE_TBL")
public class PermsModuleTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5402500886663820861L;
	private Integer moduleId;
	private Byte actStatus;
	private String descr;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private Set<PermsMapPermsEndpoint> permsMapPermsEndpoints = new HashSet<PermsMapPermsEndpoint>(0);

	public PermsModuleTbl() {
	}

	public PermsModuleTbl(Byte actStatus, String descr, Date lastUpdDttm, Integer lastUpdOprid,
			Set<PermsMapPermsEndpoint> permsMapPermsEndpoints) {
		this.actStatus = actStatus;
		this.descr = descr;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MODULE_ID", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "ACT_STATUS")
	public Byte getActStatus() {
		return this.actStatus;
	}

	public void setActStatus(Byte actStatus) {
		this.actStatus = actStatus;
	}

	@Column(name = "DESCR")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsModuleTbl")
	public Set<PermsMapPermsEndpoint> getPermsMapPermsEndpoints() {
		return this.permsMapPermsEndpoints;
	}

	public void setPermsMapPermsEndpoints(Set<PermsMapPermsEndpoint> permsMapPermsEndpoints) {
		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
	}

}
