package com.med.ods.entity;
// Generated Mar 23, 2017 4:05:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsSubModuleTbl generated by hbm2java
 */
@Entity
@Table(name = "PERMS_SUB_MODULE_TBL")
public class PermsSubModuleTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1160860065297428366L;
	private Integer subModuleId;
	private Boolean actStatus;
	private String descr;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private Set<PermsMapPermsEndpoint> permsMapPermsEndpoints = new HashSet<PermsMapPermsEndpoint>(0);

	public PermsSubModuleTbl() {
	}

	public PermsSubModuleTbl(Boolean actStatus, String descr, Date lastUpdDttm, Integer lastUpdOprid,
			Set<PermsMapPermsEndpoint> permsMapPermsEndpoints) {
		this.actStatus = actStatus;
		this.descr = descr;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SUB_MODULE__ID", unique = true, nullable = false)
	public Integer getSubModuleId() {
		return this.subModuleId;
	}

	public void setSubModuleId(Integer subModuleId) {
		this.subModuleId = subModuleId;
	}

	@Column(name = "ACT_STATUS")
	public Boolean getActStatus() {
		return this.actStatus;
	}

	public void setActStatus(Boolean actStatus) {
		this.actStatus = actStatus;
	}

	@Column(name = "DESCR")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsSubModuleTbl")
	public Set<PermsMapPermsEndpoint> getPermsMapPermsEndpoints() {
		return this.permsMapPermsEndpoints;
	}

	public void setPermsMapPermsEndpoints(Set<PermsMapPermsEndpoint> permsMapPermsEndpoints) {
		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
	}

}
