package com.med.ods.entity;
// Generated Mar 22, 2017 6:49:41 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsPersGroupTbl generated by hbm2java
 */
@Entity
@Table(name = "PERMS_PERS_GROUP_TBL")
public class PermsPersGroupTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7561100272424341853L;
	private String permsPersGroupId;
	private PermsListTbl permsListTbl;
	private String groupName;
	private String descr;
	private String type;
	private Date lastUpdDttm;
	private Integer lastUpdOrid;
//	private Set<WorkflowConstants> workflowConstantses = new HashSet<WorkflowConstants>(0);
	private Set<PermsPersGroup> permsPersGroups = new HashSet<PermsPersGroup>(0);

	public PermsPersGroupTbl() {
	}

	public PermsPersGroupTbl(String permsPersGroupId) {
		this.permsPersGroupId = permsPersGroupId;
	}

	public PermsPersGroupTbl(String permsPersGroupId, PermsListTbl permsListTbl, String groupName, String descr,
			String type, Date lastUpdDttm, Integer lastUpdOrid, /*Set<WorkflowConstants> workflowConstantses,*/
			Set<PermsPersGroup> permsPersGroups) {
		this.permsPersGroupId = permsPersGroupId;
		this.permsListTbl = permsListTbl;
		this.groupName = groupName;
		this.descr = descr;
		this.type = type;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOrid = lastUpdOrid;
//		this.workflowConstantses = workflowConstantses;
		this.permsPersGroups = permsPersGroups;
	}

	@Id

	@Column(name = "PERMS_PERS_GROUP_ID", unique = true, nullable = false, length = 10)
	public String getPermsPersGroupId() {
		return this.permsPersGroupId;
	}

	public void setPermsPersGroupId(String permsPersGroupId) {
		this.permsPersGroupId = permsPersGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMS_LIST_ID")
	public PermsListTbl getPermsListTbl() {
		return this.permsListTbl;
	}

	public void setPermsListTbl(PermsListTbl permsListTbl) {
		this.permsListTbl = permsListTbl;
	}

	@Column(name = "GROUP_NAME", length = 45)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "DESCR")
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name = "TYPE", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_ORID")
	public Integer getLastUpdOrid() {
		return this.lastUpdOrid;
	}

	public void setLastUpdOrid(Integer lastUpdOrid) {
		this.lastUpdOrid = lastUpdOrid;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsPersGroupTbl")
//	public Set<WorkflowConstants> getWorkflowConstantses() {
//		return this.workflowConstantses;
//	}
//
//	public void setWorkflowConstantses(Set<WorkflowConstants> workflowConstantses) {
//		this.workflowConstantses = workflowConstantses;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permsPersGroupTbl", cascade = CascadeType.ALL)
	public Set<PermsPersGroup> getPermsPersGroups() {
		return this.permsPersGroups;
	}

	public void setPermsPersGroups(Set<PermsPersGroup> permsPersGroups) {
		this.permsPersGroups = permsPersGroups;
	}

}
