package com.med.ods.entity;
// Generated Mar 23, 2017 4:05:48 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsMapPermsEndpoint generated by hbm2java
 */
@Entity
@Table(name = "PERMS_MAP_PERMS_ENDPOINT")
public class PermsMapPermsEndpoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6535636559743300772L;
	private Integer permsMapPermsEndpointId;
	private PermsModuleTbl permsModuleTbl;
	private PermsSubModuleTbl permsSubModuleTbl;
	private PermsTbl permsTbl;
	private TaskEndpoint taskEndpoint;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;

	public PermsMapPermsEndpoint() {
	}

	public PermsMapPermsEndpoint(PermsModuleTbl permsModuleTbl, PermsSubModuleTbl permsSubModuleTbl, PermsTbl permsTbl,
			TaskEndpoint taskEndpoint, Date lastUpdDttm, Integer lastUpdOprid) {
		this.permsModuleTbl = permsModuleTbl;
		this.permsSubModuleTbl = permsSubModuleTbl;
		this.permsTbl = permsTbl;
		this.taskEndpoint = taskEndpoint;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERMS_MAP_PERMS_ENDPOINT_ID", unique = true, nullable = false)
	public Integer getPermsMapPermsEndpointId() {
		return this.permsMapPermsEndpointId;
	}

	public void setPermsMapPermsEndpointId(Integer permsMapPermsEndpointId) {
		this.permsMapPermsEndpointId = permsMapPermsEndpointId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_ID")
	public PermsModuleTbl getPermsModuleTbl() {
		return this.permsModuleTbl;
	}

	public void setPermsModuleTbl(PermsModuleTbl permsModuleTbl) {
		this.permsModuleTbl = permsModuleTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUB_MODULE_ID")
	public PermsSubModuleTbl getPermsSubModuleTbl() {
		return this.permsSubModuleTbl;
	}

	public void setPermsSubModuleTbl(PermsSubModuleTbl permsSubModuleTbl) {
		this.permsSubModuleTbl = permsSubModuleTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMS_ID")
	public PermsTbl getPermsTbl() {
		return this.permsTbl;
	}

	public void setPermsTbl(PermsTbl permsTbl) {
		this.permsTbl = permsTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENDPOINT_ID")
	public TaskEndpoint getTaskEndpoint() {
		return this.taskEndpoint;
	}

	public void setTaskEndpoint(TaskEndpoint taskEndpoint) {
		this.taskEndpoint = taskEndpoint;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

}
