package com.med.ods.entity;
// Generated Dec 19, 2016 4:16:39 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermsPersGroupId generated by hbm2java
 */
@Embeddable
public class PermsPersGroupId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8956286705534191021L;
	private int persId;
	private String permsPersGroupId;

	public PermsPersGroupId() {
	}

	public PermsPersGroupId(int persId, String permsPersGroupId) {
		this.persId = persId;
		this.permsPersGroupId = permsPersGroupId;
	}

	@Column(name = "PERS_ID", nullable = false)
	public int getPersId() {
		return this.persId;
	}

	public void setPersId(int persId) {
		this.persId = persId;
	}

	@Column(name = "PERMS_PERS_GROUP_ID", nullable = false, length = 10)
	public String getPermsPersGroupId() {
		return this.permsPersGroupId;
	}

	public void setPermsPersGroupId(String permsPersGroupId) {
		this.permsPersGroupId = permsPersGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermsPersGroupId))
			return false;
		PermsPersGroupId castOther = (PermsPersGroupId) other;

		return (this.getPersId() == castOther.getPersId())
				&& ((this.getPermsPersGroupId() == castOther.getPermsPersGroupId())
						|| (this.getPermsPersGroupId() != null && castOther.getPermsPersGroupId() != null
								&& this.getPermsPersGroupId().equals(castOther.getPermsPersGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersId();
		result = 37 * result + (getPermsPersGroupId() == null ? 0 : this.getPermsPersGroupId().hashCode());
		return result;
	}

}
