package com.med.ods.entity;
// Generated Dec 19, 2016 4:16:39 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermsList generated by hbm2java
 */
@Entity
@Table(name = "PERMS_LIST")
public class PermsList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8391661211300624223L;
	private PermsListId id;
	private PermsListTbl permsListTbl;
	private PermsTbl permsTbl;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;

	public PermsList() {
	}

	public PermsList(PermsListId id, PermsListTbl permsListTbl, PermsTbl permsTbl) {
		this.id = id;
		this.permsListTbl = permsListTbl;
		this.permsTbl = permsTbl;
	}

	public PermsList(PermsListId id, PermsListTbl permsListTbl, PermsTbl permsTbl, Date lastUpdDttm,
			Integer lastUpdOprid) {
		this.id = id;
		this.permsListTbl = permsListTbl;
		this.permsTbl = permsTbl;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "permsListId", column = @Column(name = "PERMS_LIST_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "permsId", column = @Column(name = "PERMS_ID", nullable = false, length = 10)) })
	public PermsListId getId() {
		return this.id;
	}

	public void setId(PermsListId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMS_LIST_ID", nullable = false, insertable = false, updatable = false)
	public PermsListTbl getPermsListTbl() {
		return this.permsListTbl;
	}

	public void setPermsListTbl(PermsListTbl permsListTbl) {
		this.permsListTbl = permsListTbl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMS_ID", nullable = false, insertable = false, updatable = false)
	public PermsTbl getPermsTbl() {
		return this.permsTbl;
	}

	public void setPermsTbl(PermsTbl permsTbl) {
		this.permsTbl = permsTbl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

}
