package com.med.ods.entity;
// Generated Aug 31, 2017 2:07:20 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersLoginDevice generated by hbm2java
 */
@Entity
@Table(name = "PERS_LOGIN_DEVICE")
public class PersLoginDevice implements java.io.Serializable {

	private Integer persLoginDevice;
	private Person person;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private String regisToken;
	private String platform;
	private String connectionType;
	private Date connectDate;
	private Integer acceptFlag;
	private Set<NotiSubscrPerson> notiSubscrPersons = new HashSet<NotiSubscrPerson>(0);

	public PersLoginDevice() {
	}

	public PersLoginDevice(Person person) {
		this.person = person;
	}

	public PersLoginDevice(Person person, Date lastUpdDttm, Integer lastUpdOprid, String regisToken, String platform,
			String connectionType, Date connectDate, Set<NotiSubscrPerson> notiSubscrPersons) {
		this.person = person;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
		this.regisToken = regisToken;
		this.platform = platform;
		this.connectionType = connectionType;
		this.connectDate = connectDate;
		this.notiSubscrPersons = notiSubscrPersons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERS_LOGIN_DEVICE", unique = true, nullable = false)
	public Integer getPersLoginDevice() {
		return this.persLoginDevice;
	}

	public void setPersLoginDevice(Integer persLoginDevice) {
		this.persLoginDevice = persLoginDevice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERS_ID", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@Column(name = "REGIS_TOKEN", length = 65535)
	public String getRegisToken() {
		return this.regisToken;
	}

	public void setRegisToken(String regisToken) {
		this.regisToken = regisToken;
	}

	@Column(name = "PLATFORM")
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "CONNECTION_TYPE")
	public String getConnectionType() {
		return this.connectionType;
	}

	public void setConnectionType(String connectionType) {
		this.connectionType = connectionType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CONNECT_DATE", length = 10)
	public Date getConnectDate() {
		return this.connectDate;
	}

	public void setConnectDate(Date connectDate) {
		this.connectDate = connectDate;
	}
	
	@Column(name = "ACCEPT_FLAG")
	public Integer getAcceptFlag() {
		return acceptFlag;
	}

	public void setAcceptFlag(Integer acceptFlag) {
		this.acceptFlag = acceptFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persLoginDevice")
	public Set<NotiSubscrPerson> getNotiSubscrPersons() {
		return this.notiSubscrPersons;
	}

	public void setNotiSubscrPersons(Set<NotiSubscrPerson> notiSubscrPersons) {
		this.notiSubscrPersons = notiSubscrPersons;
	}

}
