package com.med.ods.entity;
// Generated May 24, 2017 2:16:02 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PersonCurrent generated by hbm2java
 */
@Entity
@Table(name = "PERSON_CURRENT")
public class PersonCurrent implements java.io.Serializable {

	private int persId;
//	private AddrAmphurTbl addrAmphurTblByAmphurIdType2;
//	private AddrAmphurTbl addrAmphurTblByAmphurIdType0;
//	private AddrAmphurTbl addrAmphurTblByAmphurIdType1;
//	private AddrCountryTbl addrCountryTblByCountryIdType2;
//	private AddrCountryTbl addrCountryTblByCountryIdType1;
//	private AddrCountryTbl addrCountryTblByCountryIdType0;
//	private AddrDistrictTbl addrDistrictTblByDistrictIdType0;
//	private AddrDistrictTbl addrDistrictTblByDistrictIdType2;
//	private AddrDistrictTbl addrDistrictTblByDistrictIdType1;
//	private AddrProvinceTbl addrProvinceTblByProvinceIdType2;
//	private AddrProvinceTbl addrProvinceTblByProvinceIdType1;
//	private AddrProvinceTbl addrProvinceTblByProvinceIdType0;
//	private MarStatusTbl marStatusTbl;
	private Person person;
	private Date effdt;
	private String prefix;
	private String firstName;
	private String lastName;
	private String persNickname;
	private String firstNameEn;
	private String lastNameEn;
	private String persNicknameEn;
	private String picturePath;
	private String picturePathPrivate;
	private String gender;
	private Date marStatusDt;
	private String erImmunization;
	private String erImmunizationDescr;
	private String address1Type0;
	private String zipcodeType0;
	private String address1Type1;
	private String zipcodeType1;
	private String address1Type2;
	private String zipcodeType2;
	private String emailAddress1;
	private String emailAddress2;
	private String phoneNbr;
	private String phoneExt;
	private String mobileNbr1;
	private String mobileNbr2;
	private String mobileNbr3;
	private String mobileNbr4;
	private String mobileNbr5;
	private String lineId;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
	private String aslUserId;

	public PersonCurrent() {
	}

	public PersonCurrent(Person person) {
		this.person = person;
	}

	public PersonCurrent(/*AddrAmphurTbl addrAmphurTblByAmphurIdType2, AddrAmphurTbl addrAmphurTblByAmphurIdType0,
			AddrAmphurTbl addrAmphurTblByAmphurIdType1, AddrCountryTbl addrCountryTblByCountryIdType2,
			AddrCountryTbl addrCountryTblByCountryIdType1, AddrCountryTbl addrCountryTblByCountryIdType0,
			AddrDistrictTbl addrDistrictTblByDistrictIdType0, AddrDistrictTbl addrDistrictTblByDistrictIdType2,
			AddrDistrictTbl addrDistrictTblByDistrictIdType1, AddrProvinceTbl addrProvinceTblByProvinceIdType2,
			AddrProvinceTbl addrProvinceTblByProvinceIdType1, AddrProvinceTbl addrProvinceTblByProvinceIdType0,
			MarStatusTbl marStatusTbl,*/ Person person, Date effdt, String prefix, String firstName, String lastName,
			String persNickname, String firstNameEn, String lastNameEn, String persNicknameEn, String picturePath,
			String picturePathPrivate, String gender, Date marStatusDt, String erImmunization,
			String erImmunizationDescr, String address1Type0, String zipcodeType0, String address1Type1,
			String zipcodeType1, String address1Type2, String zipcodeType2, String emailAddress1, String emailAddress2,
			String phoneNbr, String phoneExt, String mobileNbr1, String mobileNbr2, String mobileNbr3,
			String mobileNbr4, String mobileNbr5, String lineId, Date lastUpdDttm, Integer lastUpdOprid,String aslUserId) {
//		this.addrAmphurTblByAmphurIdType2 = addrAmphurTblByAmphurIdType2;
//		this.addrAmphurTblByAmphurIdType0 = addrAmphurTblByAmphurIdType0;
//		this.addrAmphurTblByAmphurIdType1 = addrAmphurTblByAmphurIdType1;
//		this.addrCountryTblByCountryIdType2 = addrCountryTblByCountryIdType2;
//		this.addrCountryTblByCountryIdType1 = addrCountryTblByCountryIdType1;
//		this.addrCountryTblByCountryIdType0 = addrCountryTblByCountryIdType0;
//		this.addrDistrictTblByDistrictIdType0 = addrDistrictTblByDistrictIdType0;
//		this.addrDistrictTblByDistrictIdType2 = addrDistrictTblByDistrictIdType2;
//		this.addrDistrictTblByDistrictIdType1 = addrDistrictTblByDistrictIdType1;
//		this.addrProvinceTblByProvinceIdType2 = addrProvinceTblByProvinceIdType2;
//		this.addrProvinceTblByProvinceIdType1 = addrProvinceTblByProvinceIdType1;
//		this.addrProvinceTblByProvinceIdType0 = addrProvinceTblByProvinceIdType0;
//		this.marStatusTbl = marStatusTbl;
		this.person = person;
		this.effdt = effdt;
		this.prefix = prefix;
		this.firstName = firstName;
		this.lastName = lastName;
		this.persNickname = persNickname;
		this.firstNameEn = firstNameEn;
		this.lastNameEn = lastNameEn;
		this.persNicknameEn = persNicknameEn;
		this.picturePath = picturePath;
		this.picturePathPrivate = picturePathPrivate;
		this.gender = gender;
		this.marStatusDt = marStatusDt;
		this.erImmunization = erImmunization;
		this.erImmunizationDescr = erImmunizationDescr;
		this.address1Type0 = address1Type0;
		this.zipcodeType0 = zipcodeType0;
		this.address1Type1 = address1Type1;
		this.zipcodeType1 = zipcodeType1;
		this.address1Type2 = address1Type2;
		this.zipcodeType2 = zipcodeType2;
		this.emailAddress1 = emailAddress1;
		this.emailAddress2 = emailAddress2;
		this.phoneNbr = phoneNbr;
		this.phoneExt = phoneExt;
		this.mobileNbr1 = mobileNbr1;
		this.mobileNbr2 = mobileNbr2;
		this.mobileNbr3 = mobileNbr3;
		this.mobileNbr4 = mobileNbr4;
		this.mobileNbr5 = mobileNbr5;
		this.lineId = lineId;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
		this.aslUserId = aslUserId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PERS_ID", unique = true, nullable = false)
	public int getPersId() {
		return this.persId;
	}

	public void setPersId(int persId) {
		this.persId = persId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "AMPHUR_ID_TYPE2")
//	public AddrAmphurTbl getAddrAmphurTblByAmphurIdType2() {
//		return this.addrAmphurTblByAmphurIdType2;
//	}
//
//	public void setAddrAmphurTblByAmphurIdType2(AddrAmphurTbl addrAmphurTblByAmphurIdType2) {
//		this.addrAmphurTblByAmphurIdType2 = addrAmphurTblByAmphurIdType2;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "AMPHUR_ID_TYPE0")
//	public AddrAmphurTbl getAddrAmphurTblByAmphurIdType0() {
//		return this.addrAmphurTblByAmphurIdType0;
//	}
//
//	public void setAddrAmphurTblByAmphurIdType0(AddrAmphurTbl addrAmphurTblByAmphurIdType0) {
//		this.addrAmphurTblByAmphurIdType0 = addrAmphurTblByAmphurIdType0;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "AMPHUR_ID_TYPE1")
//	public AddrAmphurTbl getAddrAmphurTblByAmphurIdType1() {
//		return this.addrAmphurTblByAmphurIdType1;
//	}
//
//	public void setAddrAmphurTblByAmphurIdType1(AddrAmphurTbl addrAmphurTblByAmphurIdType1) {
//		this.addrAmphurTblByAmphurIdType1 = addrAmphurTblByAmphurIdType1;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "COUNTRY_ID_TYPE2")
//	public AddrCountryTbl getAddrCountryTblByCountryIdType2() {
//		return this.addrCountryTblByCountryIdType2;
//	}
//
//	public void setAddrCountryTblByCountryIdType2(AddrCountryTbl addrCountryTblByCountryIdType2) {
//		this.addrCountryTblByCountryIdType2 = addrCountryTblByCountryIdType2;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "COUNTRY_ID_TYPE1")
//	public AddrCountryTbl getAddrCountryTblByCountryIdType1() {
//		return this.addrCountryTblByCountryIdType1;
//	}
//
//	public void setAddrCountryTblByCountryIdType1(AddrCountryTbl addrCountryTblByCountryIdType1) {
//		this.addrCountryTblByCountryIdType1 = addrCountryTblByCountryIdType1;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "COUNTRY_ID_TYPE0")
//	public AddrCountryTbl getAddrCountryTblByCountryIdType0() {
//		return this.addrCountryTblByCountryIdType0;
//	}
//
//	public void setAddrCountryTblByCountryIdType0(AddrCountryTbl addrCountryTblByCountryIdType0) {
//		this.addrCountryTblByCountryIdType0 = addrCountryTblByCountryIdType0;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "DISTRICT_ID_TYPE0")
//	public AddrDistrictTbl getAddrDistrictTblByDistrictIdType0() {
//		return this.addrDistrictTblByDistrictIdType0;
//	}
//
//	public void setAddrDistrictTblByDistrictIdType0(AddrDistrictTbl addrDistrictTblByDistrictIdType0) {
//		this.addrDistrictTblByDistrictIdType0 = addrDistrictTblByDistrictIdType0;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "DISTRICT_ID_TYPE2")
//	public AddrDistrictTbl getAddrDistrictTblByDistrictIdType2() {
//		return this.addrDistrictTblByDistrictIdType2;
//	}
//
//	public void setAddrDistrictTblByDistrictIdType2(AddrDistrictTbl addrDistrictTblByDistrictIdType2) {
//		this.addrDistrictTblByDistrictIdType2 = addrDistrictTblByDistrictIdType2;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "DISTRICT_ID_TYPE1")
//	public AddrDistrictTbl getAddrDistrictTblByDistrictIdType1() {
//		return this.addrDistrictTblByDistrictIdType1;
//	}
//
//	public void setAddrDistrictTblByDistrictIdType1(AddrDistrictTbl addrDistrictTblByDistrictIdType1) {
//		this.addrDistrictTblByDistrictIdType1 = addrDistrictTblByDistrictIdType1;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "PROVINCE_ID_TYPE2")
//	public AddrProvinceTbl getAddrProvinceTblByProvinceIdType2() {
//		return this.addrProvinceTblByProvinceIdType2;
//	}
//
//	public void setAddrProvinceTblByProvinceIdType2(AddrProvinceTbl addrProvinceTblByProvinceIdType2) {
//		this.addrProvinceTblByProvinceIdType2 = addrProvinceTblByProvinceIdType2;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "PROVINCE_ID_TYPE1")
//	public AddrProvinceTbl getAddrProvinceTblByProvinceIdType1() {
//		return this.addrProvinceTblByProvinceIdType1;
//	}
//
//	public void setAddrProvinceTblByProvinceIdType1(AddrProvinceTbl addrProvinceTblByProvinceIdType1) {
//		this.addrProvinceTblByProvinceIdType1 = addrProvinceTblByProvinceIdType1;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "PROVINCE_ID_TYPE0")
//	public AddrProvinceTbl getAddrProvinceTblByProvinceIdType0() {
//		return this.addrProvinceTblByProvinceIdType0;
//	}
//
//	public void setAddrProvinceTblByProvinceIdType0(AddrProvinceTbl addrProvinceTblByProvinceIdType0) {
//		this.addrProvinceTblByProvinceIdType0 = addrProvinceTblByProvinceIdType0;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "MAR_STATUS_ID")
//	public MarStatusTbl getMarStatusTbl() {
//		return this.marStatusTbl;
//	}
//
//	public void setMarStatusTbl(MarStatusTbl marStatusTbl) {
//		this.marStatusTbl = marStatusTbl;
//	}

	@OneToOne(fetch = FetchType.LAZY, optional = false)
	@PrimaryKeyJoinColumn
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFFDT", length = 19)
	public Date getEffdt() {
		return this.effdt;
	}

	public void setEffdt(Date effdt) {
		this.effdt = effdt;
	}

	@Column(name = "PREFIX", length = 65535)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "PERS_NICKNAME", length = 100)
	public String getPersNickname() {
		return this.persNickname;
	}

	public void setPersNickname(String persNickname) {
		this.persNickname = persNickname;
	}

	@Column(name = "FIRST_NAME_EN", length = 100)
	public String getFirstNameEn() {
		return this.firstNameEn;
	}

	public void setFirstNameEn(String firstNameEn) {
		this.firstNameEn = firstNameEn;
	}

	@Column(name = "LAST_NAME_EN", length = 100)
	public String getLastNameEn() {
		return this.lastNameEn;
	}

	public void setLastNameEn(String lastNameEn) {
		this.lastNameEn = lastNameEn;
	}

	@Column(name = "PERS_NICKNAME_EN", length = 100)
	public String getPersNicknameEn() {
		return this.persNicknameEn;
	}

	public void setPersNicknameEn(String persNicknameEn) {
		this.persNicknameEn = persNicknameEn;
	}

	@Column(name = "PICTURE_PATH", length = 65535)
	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	@Column(name = "PICTURE_PATH_PRIVATE", length = 65535)
	public String getPicturePathPrivate() {
		return this.picturePathPrivate;
	}

	public void setPicturePathPrivate(String picturePathPrivate) {
		this.picturePathPrivate = picturePathPrivate;
	}

	@Column(name = "GENDER", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MAR_STATUS_DT", length = 10)
	public Date getMarStatusDt() {
		return this.marStatusDt;
	}

	public void setMarStatusDt(Date marStatusDt) {
		this.marStatusDt = marStatusDt;
	}

	@Column(name = "ER_IMMUNIZATION", length = 45)
	public String getErImmunization() {
		return this.erImmunization;
	}

	public void setErImmunization(String erImmunization) {
		this.erImmunization = erImmunization;
	}

	@Column(name = "ER_IMMUNIZATION_DESCR", length = 65535)
	public String getErImmunizationDescr() {
		return this.erImmunizationDescr;
	}

	public void setErImmunizationDescr(String erImmunizationDescr) {
		this.erImmunizationDescr = erImmunizationDescr;
	}

	@Column(name = "ADDRESS_1_TYPE0", length = 45)
	public String getAddress1Type0() {
		return this.address1Type0;
	}

	public void setAddress1Type0(String address1Type0) {
		this.address1Type0 = address1Type0;
	}

	@Column(name = "ZIPCODE_TYPE0", length = 5)
	public String getZipcodeType0() {
		return this.zipcodeType0;
	}

	public void setZipcodeType0(String zipcodeType0) {
		this.zipcodeType0 = zipcodeType0;
	}

	@Column(name = "ADDRESS_1_TYPE1")
	public String getAddress1Type1() {
		return this.address1Type1;
	}

	public void setAddress1Type1(String address1Type1) {
		this.address1Type1 = address1Type1;
	}

	@Column(name = "ZIPCODE_TYPE1", length = 5)
	public String getZipcodeType1() {
		return this.zipcodeType1;
	}

	public void setZipcodeType1(String zipcodeType1) {
		this.zipcodeType1 = zipcodeType1;
	}

	@Column(name = "ADDRESS_1_TYPE2")
	public String getAddress1Type2() {
		return this.address1Type2;
	}

	public void setAddress1Type2(String address1Type2) {
		this.address1Type2 = address1Type2;
	}

	@Column(name = "ZIPCODE_TYPE2", length = 5)
	public String getZipcodeType2() {
		return this.zipcodeType2;
	}

	public void setZipcodeType2(String zipcodeType2) {
		this.zipcodeType2 = zipcodeType2;
	}

	@Column(name = "EMAIL_ADDRESS_1")
	public String getEmailAddress1() {
		return this.emailAddress1;
	}

	public void setEmailAddress1(String emailAddress1) {
		this.emailAddress1 = emailAddress1;
	}

	@Column(name = "EMAIL_ADDRESS_2")
	public String getEmailAddress2() {
		return this.emailAddress2;
	}

	public void setEmailAddress2(String emailAddress2) {
		this.emailAddress2 = emailAddress2;
	}

	@Column(name = "PHONE_NBR", length = 10)
	public String getPhoneNbr() {
		return this.phoneNbr;
	}

	public void setPhoneNbr(String phoneNbr) {
		this.phoneNbr = phoneNbr;
	}

	@Column(name = "PHONE_EXT", length = 10)
	public String getPhoneExt() {
		return this.phoneExt;
	}

	public void setPhoneExt(String phoneExt) {
		this.phoneExt = phoneExt;
	}

	@Column(name = "MOBILE_NBR_1", length = 10)
	public String getMobileNbr1() {
		return this.mobileNbr1;
	}

	public void setMobileNbr1(String mobileNbr1) {
		this.mobileNbr1 = mobileNbr1;
	}

	@Column(name = "MOBILE_NBR_2", length = 10)
	public String getMobileNbr2() {
		return this.mobileNbr2;
	}

	public void setMobileNbr2(String mobileNbr2) {
		this.mobileNbr2 = mobileNbr2;
	}

	@Column(name = "MOBILE_NBR_3", length = 10)
	public String getMobileNbr3() {
		return this.mobileNbr3;
	}

	public void setMobileNbr3(String mobileNbr3) {
		this.mobileNbr3 = mobileNbr3;
	}

	@Column(name = "MOBILE_NBR_4", length = 10)
	public String getMobileNbr4() {
		return this.mobileNbr4;
	}

	public void setMobileNbr4(String mobileNbr4) {
		this.mobileNbr4 = mobileNbr4;
	}

	@Column(name = "MOBILE_NBR_5", length = 10)
	public String getMobileNbr5() {
		return this.mobileNbr5;
	}

	public void setMobileNbr5(String mobileNbr5) {
		this.mobileNbr5 = mobileNbr5;
	}

	@Column(name = "LINE_ID")
	public String getLineId() {
		return this.lineId;
	}

	public void setLineId(String lineId) {
		this.lineId = lineId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@Column(name = "ASL_USER_ID")
	public String getAslUserId() {
		return aslUserId;
	}

	public void setAslUserId(String aslUserId) {
		this.aslUserId = aslUserId;
	}
	
}
