package com.med.ods.entity;
// Generated Apr 5, 2017 1:30:12 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PersAccount generated by hbm2java
 */
@Entity
@Table(name = "PERS_ACCOUNT")
public class PersAccount implements java.io.Serializable {

	private int persId;
	private Person person;
	private String username;
	private String password;
	private String salt;
	private Boolean chatAccept;
	private Boolean typeEmp;
	private String empFow;
	private Date lastUpdDttm;
	private Integer lastUpdOprid;
//	private Set<PermsPersGroup> permsPersGroups = new HashSet<PermsPersGroup>(0);

	public PersAccount() {
	}

	public PersAccount(Person person) {
		this.person = person;
	}

	public PersAccount(Person person, String username, String password, String salt, Boolean chatAccept, Boolean typeEmp,
			String empFow, Date lastUpdDttm, Integer lastUpdOprid/*, Set<PermsPersGroup> permsPersGroups*/) {
		this.person = person;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.chatAccept = chatAccept;
		this.typeEmp = typeEmp;
		this.empFow = empFow;
		this.lastUpdDttm = lastUpdDttm;
		this.lastUpdOprid = lastUpdOprid;
//		this.permsPersGroups = permsPersGroups;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PERS_ID", unique = true, nullable = false)
	public int getPersId() {
		return this.persId;
	}

	public void setPersId(int persId) {
		this.persId = persId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "USERNAME", length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SALT", length = 40)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "CHAT_ACCEPT")
	public Boolean getChatAccept() {
		return this.chatAccept;
	}

	public void setChatAccept(Boolean chatAccept) {
		this.chatAccept = chatAccept;
	}

	@Column(name = "TYPE_EMP")
	public Boolean getTypeEmp() {
		return this.typeEmp;
	}

	public void setTypeEmp(Boolean typeEmp) {
		this.typeEmp = typeEmp;
	}

	@Column(name = "EMP_FOW", length = 2)
	public String getEmpFow() {
		return this.empFow;
	}

	public void setEmpFow(String empFow) {
		this.empFow = empFow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 19)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persAccount")
//	public Set<PermsPersGroup> getPermsPersGroups() {
//		return this.permsPersGroups;
//	}
//
//	public void setPermsPersGroups(Set<PermsPersGroup> permsPersGroups) {
//		this.permsPersGroups = permsPersGroups;
//	}

}
