package com.med.ods.entity;
// Generated Oct 18, 2017 1:50:37 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResearchTbl generated by hbm2java
 */
@Entity
@Table(name = "RESEARCH_TBL")
public class ResearchTbl implements java.io.Serializable {

	private int researchId;
	private ResearchCategoryTbl researchCategoryTbl;
	private String researchName;
	private String researchSybol;
	private byte[] researchDescr;
	private byte[] researchHeader;
	private Integer researchRecommendStat;
	private String researchTragetPrice;
	private String researchMarketPrice;
	private Date researchCreateDate;
	private String researchPicture;
	private String researchAuthor;
	private Integer lastUpdOprid;
	private Date lastUpdDttm;

	public ResearchTbl() {
	}

	public ResearchTbl(int researchId) {
		this.researchId = researchId;
	}

	public ResearchTbl(int researchId, ResearchCategoryTbl researchCategoryTbl, String researchName,
			String researchSybol, byte[] researchDescr, Integer researchRecommendStat, String researchTragetPrice,
			String researchMarketPrice, Date researchCreateDate, String researchPicture, String researchAuthor,
			Integer lastUpdOprid, Date lastUpdDttm) {
		this.researchId = researchId;
		this.researchCategoryTbl = researchCategoryTbl;
		this.researchName = researchName;
		this.researchSybol = researchSybol;
		this.researchDescr = researchDescr;
		this.researchRecommendStat = researchRecommendStat;
		this.researchTragetPrice = researchTragetPrice;
		this.researchMarketPrice = researchMarketPrice;
		this.researchCreateDate = researchCreateDate;
		this.researchPicture = researchPicture;
		this.researchAuthor = researchAuthor;
		this.lastUpdOprid = lastUpdOprid;
		this.lastUpdDttm = lastUpdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RESEARCH_ID", unique = true, nullable = false)
	public int getResearchId() {
		return this.researchId;
	}

	public void setResearchId(int researchId) {
		this.researchId = researchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID")
	public ResearchCategoryTbl getResearchCategoryTbl() {
		return this.researchCategoryTbl;
	}

	public void setResearchCategoryTbl(ResearchCategoryTbl researchCategoryTbl) {
		this.researchCategoryTbl = researchCategoryTbl;
	}

	@Column(name = "RESEARCH_NAME", length = 225)
	public String getResearchName() {
		return this.researchName;
	}

	public void setResearchName(String researchName) {
		this.researchName = researchName;
	}

	@Column(name = "RESEARCH_SYBOL", length = 45)
	public String getResearchSybol() {
		return this.researchSybol;
	}

	public void setResearchSybol(String researchSybol) {
		this.researchSybol = researchSybol;
	}

	@Column(name = "RESEARCH_DESCR")
	public byte[] getResearchDescr() {
		return this.researchDescr;
	}

	public void setResearchDescr(byte[] researchDescr) {
		this.researchDescr = researchDescr;
	}
	
	@Column(name = "RESEARCH_HEADER")
	public byte[] getResearchHeader() {
		return this.researchHeader;
	}

	public void setResearchHeader(byte[] researchHeader) {
		this.researchHeader = researchHeader;
	}

	@Column(name = "RESEARCH_RECOMMEND_STAT")
	public Integer getResearchRecommendStat() {
		return this.researchRecommendStat;
	}

	public void setResearchRecommendStat(Integer researchRecommendStat) {
		this.researchRecommendStat = researchRecommendStat;
	}

	@Column(name = "RESEARCH_TRAGET_PRICE", length = 45)
	public String getResearchTragetPrice() {
		return this.researchTragetPrice;
	}

	public void setResearchTragetPrice(String researchTragetPrice) {
		this.researchTragetPrice = researchTragetPrice;
	}

	@Column(name = "RESEARCH_MARKET_PRICE", length = 45)
	public String getResearchMarketPrice() {
		return this.researchMarketPrice;
	}

	public void setResearchMarketPrice(String researchMarketPrice) {
		this.researchMarketPrice = researchMarketPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESEARCH_CREATE_DATE", length = 23)
	public Date getResearchCreateDate() {
		return this.researchCreateDate;
	}

	public void setResearchCreateDate(Date researchCreateDate) {
		this.researchCreateDate = researchCreateDate;
	}

	@Column(name = "RESEARCH_PICTURE")
	public String getResearchPicture() {
		return this.researchPicture;
	}

	public void setResearchPicture(String researchPicture) {
		this.researchPicture = researchPicture;
	}

	@Column(name = "RESEARCH_AUTHOR")
	public String getResearchAuthor() {
		return this.researchAuthor;
	}

	public void setResearchAuthor(String researchAuthor) {
		this.researchAuthor = researchAuthor;
	}

	@Column(name = "LAST_UPD_OPRID")
	public Integer getLastUpdOprid() {
		return this.lastUpdOprid;
	}

	public void setLastUpdOprid(Integer lastUpdOprid) {
		this.lastUpdOprid = lastUpdOprid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPD_DTTM", length = 23)
	public Date getLastUpdDttm() {
		return this.lastUpdDttm;
	}

	public void setLastUpdDttm(Date lastUpdDttm) {
		this.lastUpdDttm = lastUpdDttm;
	}

}
