package com.med.ods.entity;
// Generated Jan 23, 2017 10:13:44 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ServiceLog generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_LOG")
public class ServiceLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2963288561977403535L;
	private String serviceName;
	private Date timestamp;
	private String serviceGroup;

	public ServiceLog() {
	}

	public ServiceLog(String serviceName) {
		this.serviceName = serviceName;
	}

	public ServiceLog(String serviceName, String serviceGroup) {
		this.serviceName = serviceName;
		this.serviceGroup = serviceGroup;
	}

	@Id

	@Column(name = "SERVICE_NAME", unique = true, nullable = false)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMP", length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "SERVICE_GROUP")
	public String getServiceGroup() {
		return this.serviceGroup;
	}

	public void setServiceGroup(String serviceGroup) {
		this.serviceGroup = serviceGroup;
	}

}
