package com.med.ods.entity;
// Generated Jun 15, 2017 2:25:14 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaskEndpoint generated by hbm2java
 */
@Entity
@Table(name = "TASK_ENDPOINT")
public class TaskEndpoint implements java.io.Serializable {

	private Integer enptId;
	private TaskServiceTbl taskServiceTbl;
	private String enptHttpmethod;
	private String enptZone;
	private String enptName;
	private String enptPathVariableFlag;
	private String enptType;
	private String enptActFlag;
	private String enptWfFlag;
	private Boolean enptTxnLog;
//	private Set<PermsMapPermsEndpoint> permsMapPermsEndpoints = new HashSet<PermsMapPermsEndpoint>(0);

	public TaskEndpoint() {
	}

	public TaskEndpoint(String enptHttpmethod, String enptZone, String enptPathVariableFlag, String enptActFlag,
			String enptWfFlag) {
		this.enptHttpmethod = enptHttpmethod;
		this.enptZone = enptZone;
		this.enptPathVariableFlag = enptPathVariableFlag;
		this.enptActFlag = enptActFlag;
		this.enptWfFlag = enptWfFlag;
	}

	public TaskEndpoint(TaskServiceTbl taskServiceTbl, String enptHttpmethod, String enptZone, String enptName,
			String enptPathVariableFlag, String enptType, String enptActFlag, String enptWfFlag, Boolean enptTxnLog
			/*Set<PermsMapPermsEndpoint> permsMapPermsEndpoints*/) {
		this.taskServiceTbl = taskServiceTbl;
		this.enptHttpmethod = enptHttpmethod;
		this.enptZone = enptZone;
		this.enptName = enptName;
		this.enptPathVariableFlag = enptPathVariableFlag;
		this.enptType = enptType;
		this.enptActFlag = enptActFlag;
		this.enptWfFlag = enptWfFlag;
		this.enptTxnLog = enptTxnLog;
//		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ENPT_ID", unique = true, nullable = false)
	public Integer getEnptId() {
		return this.enptId;
	}

	public void setEnptId(Integer enptId) {
		this.enptId = enptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_SERVICE_ID")
	public TaskServiceTbl getTaskServiceTbl() {
		return this.taskServiceTbl;
	}

	public void setTaskServiceTbl(TaskServiceTbl taskServiceTbl) {
		this.taskServiceTbl = taskServiceTbl;
	}

	@Column(name = "ENPT_HTTPMETHOD", nullable = false, length = 10)
	public String getEnptHttpmethod() {
		return this.enptHttpmethod;
	}

	public void setEnptHttpmethod(String enptHttpmethod) {
		this.enptHttpmethod = enptHttpmethod;
	}

	@Column(name = "ENPT_ZONE", nullable = false, length = 10)
	public String getEnptZone() {
		return this.enptZone;
	}

	public void setEnptZone(String enptZone) {
		this.enptZone = enptZone;
	}

	@Column(name = "ENPT_NAME", length = 50)
	public String getEnptName() {
		return this.enptName;
	}

	public void setEnptName(String enptName) {
		this.enptName = enptName;
	}

	@Column(name = "ENPT_PATH_VARIABLE_FLAG", nullable = false, length = 1)
	public String getEnptPathVariableFlag() {
		return this.enptPathVariableFlag;
	}

	public void setEnptPathVariableFlag(String enptPathVariableFlag) {
		this.enptPathVariableFlag = enptPathVariableFlag;
	}

	@Column(name = "ENPT_TYPE", length = 10)
	public String getEnptType() {
		return this.enptType;
	}

	public void setEnptType(String enptType) {
		this.enptType = enptType;
	}

	@Column(name = "ENPT_ACT_FLAG", nullable = false, length = 1)
	public String getEnptActFlag() {
		return this.enptActFlag;
	}

	public void setEnptActFlag(String enptActFlag) {
		this.enptActFlag = enptActFlag;
	}

	@Column(name = "ENPT_WF_FLAG", nullable = false, length = 1)
	public String getEnptWfFlag() {
		return this.enptWfFlag;
	}

	public void setEnptWfFlag(String enptWfFlag) {
		this.enptWfFlag = enptWfFlag;
	}

	@Column(name = "ENPT_TXN_LOG")
	public Boolean getEnptTxnLog() {
		return this.enptTxnLog;
	}

	public void setEnptTxnLog(Boolean enptTxnLog) {
		this.enptTxnLog = enptTxnLog;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskEndpoint")
//	public Set<PermsMapPermsEndpoint> getPermsMapPermsEndpoints() {
//		return this.permsMapPermsEndpoints;
//	}
//
//	public void setPermsMapPermsEndpoints(Set<PermsMapPermsEndpoint> permsMapPermsEndpoints) {
//		this.permsMapPermsEndpoints = permsMapPermsEndpoints;
//	}

}
