package com.med.ods.entity;
// Generated Apr 11, 2017 7:38:23 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Testkey generated by hbm2java
 */
@Entity
@Table(name = "TESTKEY")
public class Testkey implements java.io.Serializable {

	private TestkeyId id;
	private String testkeyText;

	public Testkey() {
	}

	public Testkey(TestkeyId id) {
		this.id = id;
	}

	public Testkey(TestkeyId id, String testkeyText) {
		this.id = id;
		this.testkeyText = testkeyText;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "testkeyId", column = @Column(name = "TESTKEY_ID", nullable = false)),
			@AttributeOverride(name = "testkeyEffdt", column = @Column(name = "TESTKEY_EFFDT", nullable = false, length = 45)) })
	public TestkeyId getId() {
		return this.id;
	}

	public void setId(TestkeyId id) {
		this.id = id;
	}

	@Column(name = "TESTKEY_TEXT", length = 45)
	public String getTestkeyText() {
		return this.testkeyText;
	}

	public void setTestkeyText(String testkeyText) {
		this.testkeyText = testkeyText;
	}

}
