package com.med.ods.entity;
// Generated Apr 11, 2017 7:38:23 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * TestkeyId generated by hbm2java
 */
@Embeddable
public class TestkeyId implements java.io.Serializable {

	private int testkeyId;
	private String testkeyEffdt;

	public TestkeyId() {
	}

	public TestkeyId(int testkeyId, String testkeyEffdt) {
		this.testkeyId = testkeyId;
		this.testkeyEffdt = testkeyEffdt;
	}
	
	@Column(name = "TESTKEY_ID", nullable = false)
	public int getTestkeyId() {
		return this.testkeyId;
	}

	public void setTestkeyId(int testkeyId) {
		this.testkeyId = testkeyId;
	}

	@Column(name = "TESTKEY_EFFDT", nullable = false, length = 45)
	public String getTestkeyEffdt() {
		return this.testkeyEffdt;
	}

	public void setTestkeyEffdt(String testkeyEffdt) {
		this.testkeyEffdt = testkeyEffdt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestkeyId))
			return false;
		TestkeyId castOther = (TestkeyId) other;

		return (this.getTestkeyId() == castOther.getTestkeyId())
				&& ((this.getTestkeyEffdt() == castOther.getTestkeyEffdt())
						|| (this.getTestkeyEffdt() != null && castOther.getTestkeyEffdt() != null
								&& this.getTestkeyEffdt().equals(castOther.getTestkeyEffdt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTestkeyId();
		result = 37 * result + (getTestkeyEffdt() == null ? 0 : this.getTestkeyEffdt().hashCode());
		return result;
	}

}
