package com.med.ods.entity;
// Generated Jun 16, 2017 2:40:16 PM by Hibernate Tools 5.1.0.Alpha1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TxnLog generated by hbm2java
 */
@Entity
@Table(name="TXN_LOG")
public class TxnLog  implements java.io.Serializable {


     private Integer txnLogId;
     private byte[] request;
     private byte[] response;
     private String requestUrl;
     private String server;
     private String header;
     private byte[] stackTrace;
     private Integer requestOprid;
     private Date requestTime;
     private Integer executeTime;

    public TxnLog() {
    }

    public TxnLog(byte[] request, byte[] response, String requestUrl, String server, String header, byte[] stackTrace, Integer requestOprid, Date requestTime, Integer executeTime) {
       this.request = request;
       this.response = response;
       this.requestUrl = requestUrl;
       this.server = server;
       this.header = header;
       this.stackTrace = stackTrace;
       this.requestOprid = requestOprid;
       this.requestTime = requestTime;
       this.executeTime = executeTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TXN_LOG_ID", unique=true, nullable=false)
    public Integer getTxnLogId() {
        return this.txnLogId;
    }
    
    public void setTxnLogId(Integer txnLogId) {
        this.txnLogId = txnLogId;
    }

    
    @Column(name="REQUEST")
    public byte[] getRequest() {
        return this.request;
    }
    
    public void setRequest(byte[] request) {
        this.request = request;
    }

    
    @Column(name="RESPONSE")
    public byte[] getResponse() {
        return this.response;
    }
    
    public void setResponse(byte[] response) {
        this.response = response;
    }

    
    @Column(name="REQUEST_URL", length=65535)
    public String getRequestUrl() {
        return this.requestUrl;
    }
    
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    
    @Column(name="SERVER", length=100)
    public String getServer() {
        return this.server;
    }
    
    public void setServer(String server) {
        this.server = server;
    }

    
    @Column(name="HEADER", length=65535)
    public String getHeader() {
        return this.header;
    }
    
    public void setHeader(String header) {
        this.header = header;
    }

    
    @Column(name="STACK_TRACE")
    public byte[] getStackTrace() {
        return this.stackTrace;
    }
    
    public void setStackTrace(byte[] stackTrace) {
        this.stackTrace = stackTrace;
    }

    
    @Column(name="REQUEST_OPRID")
    public Integer getRequestOprid() {
        return this.requestOprid;
    }
    
    public void setRequestOprid(Integer requestOprid) {
        this.requestOprid = requestOprid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_TIME", length=19)
    public Date getRequestTime() {
        return this.requestTime;
    }
    
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    
    @Column(name="EXECUTE_TIME")
    public Integer getExecuteTime() {
        return this.executeTime;
    }
    
    public void setExecuteTime(Integer executeTime) {
        this.executeTime = executeTime;
    }




}


